Repository Selleo/til, pull requests merged in 2020-04, with the labels that each got.

#15 Fe posts for users
  frontend/src/App.js
  frontend/src/components/Categories.js
  frontend/src/components/Likes.js
  frontend/src/components/MainRoutes.js
  frontend/src/components/Posts.js
  frontend/src/components/SideBar.js
  frontend/src/components/Stats.js
  frontend/src/components/UsersPosts.js
  frontend/src/store/actionTypes.js
  frontend/src/store/actions/actions.js
  frontend/src/store/reducers/reducers.js
  frontend/src/utils.js
Labels: ready for merge 🎉

#17 Fe user profile
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/authenticated/AddPost.js
  frontend/src/authenticated/AdminPanel.js
  frontend/src/authenticated/DeleteModal.js
  frontend/src/authenticated/DeletePost.js
  frontend/src/authenticated/EditPost.js
  frontend/src/authenticated/ProfilePosts.js
  frontend/src/authenticated/UserProfile.js
  frontend/src/authenticated/index.js
  frontend/src/components/MainRoutes.js
  frontend/src/components/Post.js
  frontend/src/components/PostsList.js
  frontend/src/components/Stats.js
  frontend/src/store/actionTypes.js
  frontend/src/store/actions/actions.js
  frontend/src/store/reducers/reducers.js
Labels: ready for merge 🎉

#16 Change likes to reactions and categoriesIds to categoryIds
  backend/lib/til/activities.ex
  backend/lib/til/activities/like.ex
  backend/lib/til/activities/reaction.ex
  backend/lib/til/shareable_content.ex
  backend/lib/til/shareable_content/post.ex
  backend/lib/til_web/controllers/posts/reaction_controller.ex
  backend/lib/til_web/router.ex
  backend/lib/til_web/views/like_view.ex
  backend/lib/til_web/views/post_view.ex
  backend/lib/til_web/views/reaction_view.ex
  backend/priv/repo/migrations/20200401144955_change_likes_for_reactions.exs
  backend/test/support/factory.ex
  backend/test/til_web/controllers/activities/like_controller_test.exs
  backend/test/til_web/controllers/activities/reaction_controller_test.exs
  backend/test/til_web/controllers/post_controller_test.exs
  frontend/src/authenticated/AddPost.js
  frontend/src/authenticated/EditPost.js
Labels: ready for merge 🎉

#20 Fe reactions
  backend/mix.lock
  frontend/src/authenticated/DeletePost.js
  frontend/src/components/Post.js
  frontend/src/components/Reaction.js
  frontend/src/components/ReactionBar.js
  frontend/src/dummyData.js
  frontend/src/utils.js
Labels: ready for merge 🎉

#21 Add readme with .env template
  README.md
  backend/.env.template
  frontend/package-lock.json
Labels: ready for CR/QA 🛂

#19 Posts for review
  backend/config/config.exs
  backend/config/test.exs
  backend/docker-compose.yml
  backend/lib/til/accounts.ex
  backend/lib/til/application.ex
  backend/lib/til/mocks/httpoison_mock.ex
  backend/lib/til/notifications.ex
  backend/lib/til/notifications/notification_supervisor.ex
  backend/lib/til/notifications/slack_notifier.ex
  backend/lib/til/shareable_content.ex
  backend/lib/til/shareable_content/post.ex
  backend/lib/til_web/controllers/auth_controller.ex
  backend/lib/til_web/controllers/category_controller.ex
  backend/lib/til_web/controllers/me/post_controller.ex
  backend/lib/til_web/controllers/me_controller.ex
  backend/lib/til_web/controllers/post_controller.ex
  backend/lib/til_web/controllers/posts/reaction_controller.ex
  backend/lib/til_web/controllers/posts/review_controller.ex
  backend/lib/til_web/controllers/user_controller.ex
  backend/lib/til_web/guardian.ex
  backend/lib/til_web/plug/auth_info_pipeline.ex
  backend/lib/til_web/router.ex
  backend/lib/til_web/views/category_view.ex
  backend/lib/til_web/views/post_view.ex
  backend/lib/til_web/views/reaction_view.ex
  backend/mix.exs
  backend/mix.lock
  backend/priv/repo/migrations/20200409100111_add_reviewed_to_posts.exs
  backend/test/support/factory.ex
  backend/test/til/notifications_test.exs
  backend/test/til/policies/post_policy_test.exs
  backend/test/til_web/controllers/auth_controller_test.exs
  backend/test/til_web/controllers/me/post_controller_test.exs
  backend/test/til_web/controllers/me_controller_test.exs
  backend/test/til_web/controllers/post_controller_test.exs
  backend/test/til_web/controllers/posts/reaction_controller_test.exs
  backend/test/til_web/controllers/posts/review_controller_test.exs
  backend/test/til_web/controllers/user_controller_test.exs
Labels: ready for CR/QA 🛂

#23 Be adding custom categories
  backend/lib/til/shareable_content.ex
  backend/lib/til/shareable_content/category.ex
  backend/lib/til_web/views/post_view.ex
  backend/priv/repo/migrations/20200409121902_add_official_to_categories.exs
  backend/priv/repo/seeds.exs
  backend/test/support/factory.ex
  backend/test/til_web/controllers/me/post_controller_test.exs
  backend/test/til_web/controllers/post_controller_test.exs
Labels: ready for merge 🎉

#24 Fe post for review
  backend/lib/til_web/controllers/posts/review_controller.ex
  backend/lib/til_web/router.ex
  backend/lib/til_web/views/post_view.ex
  backend/mix.lock
  backend/test/til_web/controllers/posts/review_controller_test.exs
  frontend/src/authenticated/AddPost.js
  frontend/src/authenticated/ReviewPost.js
  frontend/src/authenticated/UserProfile.js
  frontend/src/authenticated/index.js
  frontend/src/utils.js
Labels: ready for merge 🎉

#27 Clean controllers and unify errors
  backend/lib/til/activities.ex
  backend/lib/til/shareable_content.ex
  backend/lib/til_web/controllers/category_controller.ex
  backend/lib/til_web/controllers/fallback_controller.ex
  backend/lib/til_web/controllers/me/post_controller.ex
  backend/lib/til_web/controllers/post_controller.ex
  backend/lib/til_web/controllers/posts/reaction_controller.ex
  backend/lib/til_web/controllers/posts/review_controller.ex
  backend/lib/til_web/plug/auth_error_handler.ex
  backend/lib/til_web/views/error_view.ex
  backend/test/til_web/controllers/me/post_controller_test.exs
  backend/test/til_web/controllers/me_controller_test.exs
  backend/test/til_web/controllers/post_controller_test.exs
  backend/test/til_web/controllers/posts/reaction_controller_test.exs
  backend/test/til_web/controllers/posts/review_controller_test.exs
  frontend/src/authenticated/ReviewPost.js
Labels: ready for CR/QA 🛂

#26 Be statistics for users
  backend/lib/til/accounts.ex
  backend/lib/til/statistics.ex
  backend/lib/til/statistics/user_statistics.ex
  backend/lib/til_web/controllers/statistics/user_statistics_controller.ex
  backend/lib/til_web/router.ex
  backend/lib/til_web/views/statistics/user_statistics_view.ex
  backend/test/til_web/controllers/statistics/user_statistics_controller_test.exs
  backend/test/til_web/controllers/user_controller_test.exs
Labels: ready for merge 🎉

#30 fix: auth flow
  frontend/src/App.js
  frontend/src/authenticated/AddPost.js
  frontend/src/authenticated/AdminPanel.js
  frontend/src/authenticated/EditPost.js
  frontend/src/authenticated/Logout.js
  frontend/src/authenticated/ReviewPost.js
  frontend/src/authenticated/UserProfile.js
  frontend/src/authenticated/index.js
  frontend/src/components/AuthHandler.js
  frontend/src/components/DisplayPost.js
  frontend/src/components/Post.js
  frontend/src/components/PostCategories.js
  frontend/src/components/ReactionBar.js
  frontend/src/components/SideBar.js
  frontend/src/store/actionTypes.js
  frontend/src/store/actions/actions.js
  frontend/src/store/reducers/reducers.js
  frontend/src/utils/auth.js
  frontend/src/utils/index.js
  frontend/src/utils/posts/CRUDposts.js
Labels: do not merge ⛔️, new feedback

#32 Fe statistics
  frontend/src/authenticated/DeletePost.js
  frontend/src/components/DisplayPost.js
  frontend/src/components/PostCategories.js
  frontend/src/components/Stats.js
  frontend/src/components/UsersPosts.js
  frontend/src/store/actions/actions.js
  frontend/src/utils/posts/CRUDposts.js
Labels: do not merge ⛔️, new feedback

#33 Fe search
  backend/priv/repo/seeds.exs
  frontend/.vscode/launch.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/authenticated/ReviewPost.js
  frontend/src/components/DisplayPost.js
  frontend/src/components/Likes.js
  frontend/src/components/MainRoutes.js
  frontend/src/components/Markdown.js
  frontend/src/components/Post.js
  frontend/src/components/PostsList.js
  frontend/src/components/Search.js
  frontend/src/components/SearchedPosts.js
  frontend/src/components/SideBar.js
  frontend/src/components/TextBlock.js
  frontend/src/store/actionTypes.js
  frontend/src/store/actions/actions.js
  frontend/src/store/reducers/reducers.js
  frontend/src/utils/customHooks/onRouteLeave.js
  frontend/src/utils/index.js
  frontend/src/utils/posts/searchPosts.js
Labels: ready for merge 🎉

#37 Fe toasts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/authenticated/AddPost.js
  frontend/src/authenticated/DeletePost.js
  frontend/src/authenticated/EditPost.js
  frontend/src/authenticated/UserProfile.js
  frontend/src/authenticated/index.js
  frontend/src/components/Reaction.js
  frontend/src/components/Search.js
  frontend/src/components/SideBar.js
  frontend/src/utils/customHooks/useOnRouteLeave.js
  frontend/src/utils/customHooks/useUser.js
  frontend/src/utils/posts/CRUDposts.js
  frontend/src/utils/toasts/errorToast.js
  frontend/src/utils/toasts/postSuccessToast.js
Labels: ready for merge 🎉
